import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Shoppinglist',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <meta name="apple-mobile-web-app-title" content="Shoppinglist" />
      <body>{children}</body>
    </html>
  )
}
